backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/uploads
public_folder: /uploads

collections:
  - label: 'Page Details'
    name: 'details'
    files: 
      - label: 'Hone'
        name: 'Home'
        file: 'content/home.yml'
        fields: 
          - {label: 'Welcome Message', name: 'welcome', widget: 'text'}
      - label: 'About'
        name: 'About'
        file: 'about.yml'
        fields: 
          - {label: 'About Message', name: 'about', widget: 'text'}
      - label: 'Contact'
        name: 'Contact'
        file: 'contact.yml'
        fields: 
          - {label: 'Name', name: 'name', widget: 'string'}
          - {label: 'Content', name: 'content', widget: 'text'}
          - {label: 'Phone', name: 'phone', widget: 'string'}
          - {label: 'Fax', name: 'fax', widget: 'string'}
          - {label: 'Document Exchange', name: 'documentexchange', widget: 'string'}
          - {label: 'Email', name: 'email', widget: 'string'}

  - label: 'Areas of Practice'
    name: 'aop'
    create: true
    folder: 'content/aop'
    fields: 
     - {label: 'Area of Practice', name: 'aop', widget: 'string'}
  
  - label: 'Barristers'
    name: 'barristers'
    create: true
    folder: 'content/barristers'
    fields:
      - {label: 'Name', name: 'name', widget: 'string'}
      - {label: 'Content', name: 'content', widget: 'text'}
      - {label: 'Phone', name: 'phone', widget: 'string'}
      - {label: 'Fax', name: 'fax', widget: 'string'}
      - {label: 'Email', name: 'email', widget: 'string'}
      - {label: 'Areas of Practice', name: aops, widget: relation, multiple: true, collection: 'aop', value_field: 'aop', search_field: 'aop'}